# Generated by Django 4.0.2 on 2022-07-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
