# Generated by Django 4.0.2 on 2022-07-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_date_created_alter_notes_last_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Author',
            new_name='author',
        ),
    ]
