# Generated by Django 4.0.2 on 2022-07-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_author_notes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=models.CharField(choices=[('r', 'Red'), ('b', 'Blue'), ('w', 'White')], default='w', max_length=1),
        ),
    ]
